#!/bin/sh
# Xcode Cloud post-clone script
# Writes API keys from environment variables into Config.local.xcconfig

echo "Writing Config.local.xcconfig from environment variables..."

cat > "$CI_PRIMARY_REPOSITORY_PATH/Config.local.xcconfig" <<EOL
// Generated by ci_post_clone.sh — do not commit
ANTHROPIC_API_KEY = ${ANTHROPIC_API_KEY}
LANGSMITH_API_KEY = ${LANGSMITH_API_KEY}
EOL

echo "Config.local.xcconfig written successfully."
