#!/bin/sh
# Xcode Cloud post-clone script
# Writes API keys and config files from environment variables

echo "CI_PRIMARY_REPOSITORY_PATH = $CI_PRIMARY_REPOSITORY_PATH"

echo "Writing Config.local.xcconfig from environment variables..."

cat > "$CI_PRIMARY_REPOSITORY_PATH/Config.local.xcconfig" <<EOL
// Generated by ci_post_clone.sh — do not commit
ANTHROPIC_API_KEY = ${ANTHROPICAPIKEY}
LANGSMITH_API_KEY = ${LANGSMITHAPIKEY}
EOL

echo "Writing Config.plist..."

cat > "$CI_PRIMARY_REPOSITORY_PATH/IronmanTrainer/Config.plist" <<EOL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ANTHROPIC_API_KEY</key>
	<string>${ANTHROPICAPIKEY}</string>
	<key>LANGSMITH_API_KEY</key>
	<string>${LANGSMITHAPIKEY}</string>
</dict>
</plist>
EOL

echo "Writing GoogleService-Info.plist..."

cat > "$CI_PRIMARY_REPOSITORY_PATH/IronmanTrainer/GoogleService-Info.plist" <<EOL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>API_KEY</key>
	<string>${FIREBASEAPIKEY}</string>
	<key>GCM_SENDER_ID</key>
	<string>469784468799</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>com.brent.ironmantrainer</string>
	<key>PROJECT_ID</key>
	<string>brents-trainer</string>
	<key>STORAGE_BUCKET</key>
	<string>brents-trainer.firebasestorage.app</string>
	<key>IS_ADS_ENABLED</key>
	<false/>
	<key>IS_ANALYTICS_ENABLED</key>
	<false/>
	<key>IS_APPINVITE_ENABLED</key>
	<true/>
	<key>IS_GCM_ENABLED</key>
	<true/>
	<key>IS_SIGNIN_ENABLED</key>
	<true/>
	<key>GOOGLE_APP_ID</key>
	<string>1:469784468799:ios:ecad30d44b4d7e5670878a</string>
</dict>
</plist>
EOL

echo "CI setup complete."
